### ISSUE TITLE
Custom characters not working

### ISSUE THREAD

**Issue by ChamelonGG** [dhalbert/CircuitPython_LCD#8]
Hi, Im running pi pico with this library to drive my 20x4 char lcd with PCF8574 bit expander on board and im having problems with displaying custom characters. The REPL console returns "can't convert 'int' object to str implicitly" every time i pass bytearray to the function

**Comment by dhalbert** [comment]
Could you show the offending code and the error?

**Comment by educ8s** [comment]
I know what is wrong since I made the same mistake myself. 

I was creating a new custom characher like this:
lcd.create_char(0,smiley)

and then I was trying to display that character like this:

lcd.write(smiley) instead of the correct call of the method,

lcd.write(0)

We have to pass in the location in the memory, not the bitmap itself. 

The library works perfectly fine! Thanks for sharing.
